esphome:
  name: elecrow-7-inch-touchscreen
  friendly_name: Elecrow 7 Inch Touchscreen
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 4MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - delay: 3s
    - component.update: dashboard_image

api:
logger:
  hardware_uart: UART0
ota:
  - platform: esphome

psram:
  mode: octal

display:
  - platform: rpi_dpi_rgb
    id: main_display
    color_order: RGB
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 800
      height: 480
    de_pin: 41
    hsync_pin: 39
    vsync_pin: 40
    pclk_pin: 0
    pclk_frequency: 15MHz
    pclk_inverted: true

    hsync_front_porch: 40
    hsync_pulse_width: 48
    hsync_back_porch: 13

    vsync_front_porch: 1
    vsync_pulse_width: 31
    vsync_back_porch: 13

    data_pins:
      red: [14, 21, 47, 48, 45]
      green: [9, 46, 3, 8, 16, 1]
      blue: [15, 7, 6, 5, 4]
    lambda: |-
      it.image(0, 0, id(dashboard_image));


http_request:
  timeout: 10s
  watchdog_timeout: 15s

online_image:
  - id: dashboard_image
    format: PNG
    type: RGB
    # Replace X.X.X.X with your IP address
    url: http://X.X.X.X:10000/dashboard-dashboards/waveshare?viewport=800x480
    on_download_finished:
      - delay: 0ms
      - component.update: main_display

output:
  - platform: ledc
    pin: 2
    id: backlight_pin

light:
  - platform: monochromatic
    output: backlight_pin
    name: "Backlight"
    restore_mode: RESTORE_DEFAULT_ON
    gamma_correct: 1.8

button:
  - platform: template
    name: Update Dashboard
    on_press:
      then:
        - component.update: dashboard_image
