name: "Puppet"
description: "Turn dashboards into nice pictures"
version: "1.19.4"
slug: "puppet"
homeassistant_api: true
init: false
arch:
  - aarch64
  - amd64
ports:
  10000/tcp: 10000
options:
  access_token: ""
  keep_browser_open: false
  home_assistant_url: ""
  home_assistant_ssl: false
schema:
  access_token: str
  keep_browser_open: bool
  home_assistant_url: str
  home_assistant_ssl: bool
